---
title: "Risk Map"
author: "Bram van Smoorenburg"
date: "3 May 2018"
output: html_document
---

data
```{r}
map=unlist(read.delim("./map.txt",header=FALSE,stringsAsFactors = FALSE))
names(map)=NULL
map=strsplit(map,";")
mapvec=sapply(map,function(x){x[1]})
map=lapply(map,function(x){x[-1]})
```

initializing distance matrix
```{r}
distan=matrix(0,length(mapvec),length(mapvec))
rownames(distan)=mapvec
colnames(distan)=mapvec
for (i in 1:nrow(distan)) {
  distan[i,map[[i]]]=1
}
if (any(distan!=t(distan))) {
  which(distan!=t(distan),arr.ind = TRUE)
  stop("distance matrix is not symmetric, wrong connection")
}
```

rest of distance matrix
```{r}
distan2=distan
while (sum(distan==0)>nrow(distan)) {
  for (i in 1:nrow(distan)) {
    neighbors=colnames(distan)[which(distan[i,]!=0)]
    for (b in neighbors) {
      tempdist=distan[b,]
      cdist=distan[i,b]
      tempdist[tempdist!=0]=tempdist[tempdist!=0]+cdist
      distan2[i,distan2[i,]==0&tempdist!=0]=Inf
      tempdist[tempdist==0]=Inf
      distan2[i,]=pmin(distan2[i,],tempdist)
      diag(distan2)=0
    }
  }
  distan=distan2
}
```

scaling
```{r}
library(smacof)
configu=mds(distan)
plot(configu)
```

discrepancies
```{r}
which(distan!=t(distan),arr.ind = TRUE)
```

all distances
```{r}
table(as.vector(distan))
```

mean distance
```{r}
sort(rowMeans(distan),decreasing = TRUE)
```

ggplot
```{r}
library(ggplot2)
p=ggplot(as.data.frame(configu$conf),aes(D1,D2))+geom_point()+geom_text(aes(label=rownames(configu$conf)),nudge_y = 0.03)
p
```


3d plot
```{r}
configu3=mds(distan,ndim = 3)
par(mfrow=c(1,2))
plot(configu3);plot(configu3,plot.dim = c(3,2))
```

3d scatterplot
```{r}
configu3m=configu3$conf
configu3m[,1]=-configu3m[,1]
library(scatterplot3d)
par(mfrow=c(1,2))
scatterplot3d(configu3$conf,pch = rownames(configu3$conf),highlight.3d = TRUE)
scatterplot3d(configu3m,pch = rownames(configu3m),highlight.3d = TRUE)
```
